apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}-nginx
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.fullName }}
    component: nginx
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.nginx.port }}
      nodePort: {{ .Values.nginx.nodePort }}
