apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}-server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.fullName }}
    component: server
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.server.port }}

